name: Checkout Workflow

on:
  workflow_dispatch:

jobs:
  checkout-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Files
        run: ls

      - name: Show Current Directory
        run: pwd