name: daily-check
on:
  schedule:
    -cron: '0 9 * * *'

jobs:
  check-pipe:
    runs-on: ubuntu-latest

    steps:
      - name: current date
        run: date

      - name: current user
        run: whoami

      - name: simple printing
        run: echo "system health check"
