name: docker-build

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: show files
        run: ls -la

      - name: build image
        run: docker build -t myapp .