name: node-app

on:
  push:

jobs:
  test-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check Node Version
        run: node --version

      - name: Check NPM Version
        run: npm --version

      - name: Print Message
        run: echo "Node.js installed successfully"